"""add and update financial fields

Revision ID: 0bbc794546e9
Revises: ac7dca694404
Create Date: 2026-08-26 11:15:41.737490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bbc794546e9'
down_revision: Union[str, Sequence[str], None] = 'ac7dca694404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'additional_fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('contracts', sa.Column('payment_day', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('contracts', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('incidents', sa.Column('repair_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'received'::character varying"))
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rooms', 'base_rent', new_column_name='cost_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'cost_price', new_column_name='base_rent')
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'received'::character varying"))
    op.drop_column('incidents', 'repair_cost')
    op.alter_column('contracts', 'notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('contracts', 'payment_day')
    op.alter_column('bills', 'additional_fee',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
