"""add new column temp_residence_expiry

Revision ID: 1238b61f9bee
Revises: bb48b3422b29
Create Date: 2026-09-23 22:07:26.610659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1238b61f9bee'
down_revision: Union[str, Sequence[str], None] = 'bb48b3422b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('temp_residence_expiry', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'temp_residence_expiry')
    # ### end Alembic commands ###
