"""add new column temp_residence_start

Revision ID: 199236426b9b
Revises: 1238b61f9bee
Create Date: 2026-09-24 10:22:21.170874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199236426b9b'
down_revision: Union[str, Sequence[str], None] = '1238b61f9bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('temp_residence_start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'temp_residence_start')
    # ### end Alembic commands ###
