"""add end_reason to contracts

Revision ID: 19a98d341a86
Revises: de9c473cb776
Create Date: 2026-07-11 14:57:57.235637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a98d341a86'
down_revision: Union[str, Sequence[str], None] = 'de9c473cb776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('end_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'end_reason')
    # ### end Alembic commands ###
