"""create new table for managing finance

Revision ID: 1a798ec648a2
Revises: 0bbc794546e9
Create Date: 2026-08-28 21:20:42.607630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a798ec648a2'
down_revision: Union[str, Sequence[str], None] = '0bbc794546e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_house_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_electric_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_electric_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_water_cube', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_water_bill', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manager_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_house_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id', 'month', name='uq_house_month_cost')
    )
    op.add_column('houses', sa.Column('employee_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('incidents', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'completed_at')
    op.drop_column('houses', 'employee_fee')
    op.drop_table('monthly_house_costs')
    # ### end Alembic commands ###
