"""remove unique constraint bill

Revision ID: 1e5fd4abd795
Revises: b352613172c3
Create Date: 2026-10-05 21:20:49.383640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5fd4abd795'
down_revision: Union[str, Sequence[str], None] = 'b352613172c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_contract_month'), 'bills', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_contract_month'), 'bills', ['contract_id', 'billing_month'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
