"""add consumed columns to bills

Revision ID: 2abe9360ce37
Revises: fd4754ae3c04
Create Date: 2026-07-02 09:41:28.116823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe9360ce37'
down_revision: Union[str, Sequence[str], None] = 'fd4754ae3c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('electric_consumed', sa.Float(), nullable=False))
    op.add_column('bills', sa.Column('water_consumed', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'water_consumed')
    op.drop_column('bills', 'electric_consumed')
    # ### end Alembic commands ###
