"""add cleaning_fee and internet_fee to contracts and bills

Revision ID: 338406937616
Revises: 9dd51797eab8
Create Date: 2026-09-09 09:43:29.021589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338406937616'
down_revision: Union[str, Sequence[str], None] = '9dd51797eab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('cleaning_fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('bills', sa.Column('internet_fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('contracts', sa.Column('cleaning_fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('contracts', sa.Column('internet_fee', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'internet_fee')
    op.drop_column('contracts', 'cleaning_fee')
    op.drop_column('bills', 'internet_fee')
    op.drop_column('bills', 'cleaning_fee')
    # ### end Alembic commands ###
