"""add houses table and house_id to rooms

Revision ID: 3a12220822f2
Revises: 19a98d341a86
Create Date: 2026-07-17 11:05:33.967321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a12220822f2'
down_revision: Union[str, Sequence[str], None] = '19a98d341a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO houses (id, name) VALUES (1, 'Nhà trọ chính')")

    op.add_column('rooms', sa.Column('house_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('rooms_house_id_fkey', 'rooms', 'houses', ['house_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_house_id_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'house_id')
    op.drop_table('houses')
    # ### end Alembic commands ###
