"""add is_water_meter to rooms and default_water_amount to utility_rates

Revision ID: 42f9acb285fa
Revises: 2abe9360ce37
Create Date: 2026-07-05 21:01:38.091942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f9acb285fa'
down_revision: Union[str, Sequence[str], None] = '2abe9360ce37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_water_meter', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('utility_rates', sa.Column('default_water_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utility_rates', 'default_water_amount')
    op.drop_column('rooms', 'is_water_meter')
    # ### end Alembic commands ###
