"""update db schema

Revision ID: 549bc6bfdef2
Revises: 338406937616
Create Date: 2026-09-13 22:11:31.804588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549bc6bfdef2'
down_revision: Union[str, Sequence[str], None] = '338406937616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('id_card_number', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('temp_residence_dec', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('monthly_house_costs', sa.Column('total_internet_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.alter_column('rooms', 'furnitures', new_column_name='feature_and_furniture')
    op.alter_column('tenants', 'id_card_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'id_card_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('rooms', 'feature_and_furniture', new_column_name='furnitures')
    op.drop_column('monthly_house_costs', 'total_internet_cost')
    op.drop_column('contracts', 'temp_residence_dec')
    op.drop_table('co_tenants')
    # ### end Alembic commands ###
