"""sync current schema

Revision ID: 65c6597a3969
Revises: 3a12220822f2
Create Date: 2026-08-21 14:37:49.033145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c6597a3969'
down_revision: Union[str, Sequence[str], None] = '3a12220822f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_house',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'house_id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bills', sa.Column('additional_fee', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('bills', sa.Column('additional_fee_reason', sa.String(length=255), nullable=True))
    op.add_column('contracts', sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('contracts', sa.Column('notes', sa.String(length=500), nullable=True))
    op.alter_column('contracts', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('contracts_room_id_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.add_column('houses', sa.Column('contract_template', sa.Text(), nullable=True))
    op.add_column('houses', sa.Column('theme_color', sa.String(length=7), nullable=False, server_default='#3B82F6'))
    op.add_column('rooms', sa.Column('furnitures', sa.ARRAY(sa.String()), nullable=True))
    op.drop_constraint(op.f('rooms_room_number_key'), 'rooms', type_='unique')
    op.create_unique_constraint('uix_house_room', 'rooms', ['house_id', 'room_number'])
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('max_rooms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_rooms')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'subscription_plan')
    op.drop_constraint('uix_house_room', 'rooms', type_='unique')
    op.create_unique_constraint(op.f('rooms_room_number_key'), 'rooms', ['room_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('rooms', 'furnitures')
    op.drop_column('houses', 'theme_color')
    op.drop_column('houses', 'contract_template')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_room_id_fkey'), 'contracts', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('contracts', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('contracts', 'notes')
    op.drop_column('contracts', 'service_fee')
    op.drop_column('bills', 'additional_fee_reason')
    op.drop_column('bills', 'additional_fee')
    op.drop_table('incidents')
    op.drop_table('user_house')
    # ### end Alembic commands ###
