"""add new column due_date to bill

Revision ID: 739f2067c21e
Revises: 1e5fd4abd795
Create Date: 2026-10-06 09:50:24.337064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739f2067c21e'
down_revision: Union[str, Sequence[str], None] = '1e5fd4abd795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'due_date')
    # ### end Alembic commands ###
