"""add_other_cost_reason

Revision ID: 9dd51797eab8
Revises: 1a798ec648a2
Create Date: 2026-08-31 10:00:59.534604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd51797eab8'
down_revision: Union[str, Sequence[str], None] = '1a798ec648a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_house_costs', sa.Column('other_house_cost_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_house_costs', 'other_house_cost_reason')
    # ### end Alembic commands ###
