"""add new columns about temp_residence in co_tenants

Revision ID: a7c86f0256bd
Revises: 199236426b9b
Create Date: 2026-09-24 21:22:11.775528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c86f0256bd'
down_revision: Union[str, Sequence[str], None] = '199236426b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('co_tenants', sa.Column('temp_residence_reg', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('co_tenants', sa.Column('temp_residence_start', sa.Date(), nullable=True))
    op.add_column('co_tenants', sa.Column('temp_residence_expiry', sa.Date(), nullable=True))
    op.add_column('co_tenants', sa.Column('temp_residence_dec', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('co_tenants', 'temp_residence_dec')
    op.drop_column('co_tenants', 'temp_residence_expiry')
    op.drop_column('co_tenants', 'temp_residence_start')
    op.drop_column('co_tenants', 'temp_residence_reg')
    # ### end Alembic commands ###
