"""add new column expense_month to table incident

Revision ID: b352613172c3
Revises: e07ba29cf125
Create Date: 2026-10-02 23:16:55.303189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b352613172c3'
down_revision: Union[str, Sequence[str], None] = 'e07ba29cf125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('expense_month', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'expense_month')
    # ### end Alembic commands ###
