"""add new column discount_amount in bill

Revision ID: c524aff5fc92
Revises: 549bc6bfdef2
Create Date: 2026-09-15 15:55:21.232792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c524aff5fc92'
down_revision: Union[str, Sequence[str], None] = '549bc6bfdef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'discount_amount')
    # ### end Alembic commands ###
