"""add num_tenants num_vehicles temp_residence_reg to contracts

Revision ID: de9c473cb776
Revises: 42f9acb285fa
Create Date: 2026-07-10 08:34:37.065386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9c473cb776'
down_revision: Union[str, Sequence[str], None] = '42f9acb285fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('num_tenants', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('contracts', sa.Column('num_vehicles', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('contracts', sa.Column('temp_residence_reg', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'temp_residence_reg')
    op.drop_column('contracts', 'num_vehicles')
    op.drop_column('contracts', 'num_tenants')
    # ### end Alembic commands ###
