"""add new column discount reason in bill

Revision ID: dfeff3ad8dd9
Revises: a7c86f0256bd
Create Date: 2026-09-28 10:10:25.796366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfeff3ad8dd9'
down_revision: Union[str, Sequence[str], None] = 'a7c86f0256bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('discount_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'discount_reason')
    # ### end Alembic commands ###
