"""add new column for new electric calculation method

Revision ID: ea698fd8387a
Revises: dfeff3ad8dd9
Create Date: 2026-10-01 15:21:38.915761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea698fd8387a'
down_revision: Union[str, Sequence[str], None] = 'dfeff3ad8dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('electric_calc_method', sa.String(length=20), nullable=False, server_default=sa.text("'fixed_price'")))
    op.add_column('bills', sa.Column('electric_total_consumed', sa.Float(), nullable=True))
    op.add_column('bills', sa.Column('electric_total_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('contracts', sa.Column('electric_calc_method', sa.String(length=20), nullable=False,  server_default=sa.text("'fixed_price'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'electric_calc_method')
    op.drop_column('bills', 'electric_total_cost')
    op.drop_column('bills', 'electric_total_consumed')
    op.drop_column('bills', 'electric_calc_method')
    # ### end Alembic commands ###
